title: "Shiva Hegde"
email: shivahegde.work@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Shiva's personal portfolio page!
baseurl: "/" 
url: "/SaintNerevar.github.io" 
twitter_username: 
github_username:  SaintNerevar

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
